// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAZCCH7qDQn0__xWOl_leh98WBiQPXWpH8",
    authDomain: "crud-flutter-82603.firebaseapp.com",
    appId: "1:236915927209:web:046952ef5badefa6b7e1b8",
    messagingSenderId: "236915927209",
    projectId: "crud-flutter-82603",
    storageBucket: "crud-flutter-82603.appspot.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAZCCH7qDQn0__xWOl_leh98WBiQPXWpH8",
    appId: "1:236915927209:web:046952ef5badefa6b7e1b8",
    messagingSenderId: "236915927209",
    projectId: "crud-flutter-82603",
    storageBucket: "crud-flutter-82603.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAZCCH7qDQn0__xWOl_leh98WBiQPXWpH8",
    appId: "1:236915927209:web:046952ef5badefa6b7e1b8",
    messagingSenderId: "236915927209",
    projectId: "crud-flutter-82603",
    storageBucket: "crud-flutter-82603.appspot.com",
    iosClientId: '673111946324-l3f65k2rmp5isk1vavq1qg17dujjuo3j.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAZCCH7qDQn0__xWOl_leh98WBiQPXWpH8",
    appId: "1:236915927209:web:046952ef5badefa6b7e1b8",
    messagingSenderId: "236915927209",
    projectId: "crud-flutter-82603",
    storageBucket: "crud-flutter-82603.appspot.com",
    iosClientId: '673111946324-l3f65k2rmp5isk1vavq1qg17dujjuo3j.apps.googleusercontent.com',
    iosBundleId: 'com.codigocorrecto.crud',
  );
}
